/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cine;

import com.sun.awt.AWTUtilities;
import java.awt.Color;
import java.util.Calendar;
import javax.swing.ImageIcon;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.*;

/**
 *
 * @author Jesus David
 */
public class Admin extends javax.swing.JFrame implements Runnable {

    String hora, minutos, segundos;
    Thread hilo;

    /**
     * Creates new form LogInAdmin
     */
    public Admin() {
        initComponents();
        AWTUtilities.setWindowOpaque(this, false);
        setLocationRelativeTo(null);
        fecha.setText(Fecha());
        hilo = new Thread(this);
        hilo.start();
        setVisible(true);
        String text = "<html><body>Gestionar <br> Peliculas</body></html>";
        pdisponibles.setText(text);
    }

    public void hora() {
        Calendar cal = new GregorianCalendar();
        Date horaactual = new Date();
        cal.setTime(horaactual);
        hora = cal.get(Calendar.HOUR_OF_DAY) > 9 ? "" + cal.get(Calendar.HOUR_OF_DAY) : "0" + cal.get(Calendar.HOUR_OF_DAY);
        minutos = cal.get(Calendar.MINUTE) > 9 ? "" + cal.get(Calendar.MINUTE) : "0" + cal.get(Calendar.MINUTE);
        segundos = cal.get(Calendar.SECOND) > 9 ? "" + cal.get(Calendar.SECOND) : "0" + cal.get(Calendar.SECOND);
    }

    public void run() {
        Thread current = Thread.currentThread();
//        while(current==hilo){
//            hora();
//            hour.setText(hora+":"+minutos+":"+segundos);
//        }

        for (int i = 1; i > 0; i++) {
            if (i > 0) {
                hora();
                hour.setText(hora + ":" + minutos + ":" + segundos);
            }
        }
    }

    public static String Fecha() {
        Date fecha = new Date();
        SimpleDateFormat formatofecha = new SimpleDateFormat("dd/MM/YYYY");
        return formatofecha.format(fecha);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        logout = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        topbar = new javax.swing.JLabel();
        hour = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        agregarpelis = new javax.swing.JLabel();
        pdisponibles = new javax.swing.JLabel();
        entradas = new javax.swing.JLabel();
        horarios = new javax.swing.JLabel();
        addadmin = new javax.swing.JLabel();
        cartelera = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logout Rounded Left_25px.png"))); // NOI18N
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        background.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        close.setBackground(new java.awt.Color(255, 255, 255));
        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Delete_25px.png"))); // NOI18N
        close.setOpaque(true);
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        background.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 40, 40));

        topbar.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        topbar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                topbarMouseDragged(evt);
            }
        });
        topbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                topbarMousePressed(evt);
            }
        });
        background.add(topbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 40));

        hour.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 34)); // NOI18N
        hour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hour.setText("00:00:00");
        background.add(hour, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 150, 60));

        fecha.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        fecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fecha.setText("DD/MM/YYYY");
        background.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 170, 30));

        agregarpelis.setBackground(new java.awt.Color(255, 255, 255));
        agregarpelis.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        agregarpelis.setForeground(new java.awt.Color(153, 153, 153));
        agregarpelis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agregarpelis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Movie_85px.png"))); // NOI18N
        agregarpelis.setText("Agregar Peliculas");
        agregarpelis.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        agregarpelis.setOpaque(true);
        agregarpelis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarpelisMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                agregarpelisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                agregarpelisMouseExited(evt);
            }
        });
        background.add(agregarpelis, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 210, 100));

        pdisponibles.setBackground(new java.awt.Color(255, 255, 255));
        pdisponibles.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        pdisponibles.setForeground(new java.awt.Color(153, 153, 153));
        pdisponibles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pdisponibles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Movie Projector_85px.png"))); // NOI18N
        pdisponibles.setText("Peliculas disponibles");
        pdisponibles.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pdisponibles.setOpaque(true);
        pdisponibles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pdisponiblesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pdisponiblesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pdisponiblesMouseExited(evt);
            }
        });
        background.add(pdisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 200, 100));

        entradas.setBackground(new java.awt.Color(255, 255, 255));
        entradas.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        entradas.setForeground(new java.awt.Color(153, 153, 153));
        entradas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        entradas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/New Ticket_85px.png"))); // NOI18N
        entradas.setText("Entradas");
        entradas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        entradas.setOpaque(true);
        entradas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entradasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                entradasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                entradasMouseExited(evt);
            }
        });
        background.add(entradas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 210, 100));

        horarios.setBackground(new java.awt.Color(255, 255, 255));
        horarios.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        horarios.setForeground(new java.awt.Color(153, 153, 153));
        horarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        horarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Schedule_85px.png"))); // NOI18N
        horarios.setText("Horarios");
        horarios.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        horarios.setOpaque(true);
        horarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                horariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                horariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                horariosMouseExited(evt);
            }
        });
        background.add(horarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 210, 100));

        addadmin.setBackground(new java.awt.Color(255, 255, 255));
        addadmin.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        addadmin.setForeground(new java.awt.Color(153, 153, 153));
        addadmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addadmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Male User_85px.png"))); // NOI18N
        addadmin.setText("Registrar Admin");
        addadmin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        addadmin.setOpaque(true);
        addadmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addadminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addadminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addadminMouseExited(evt);
            }
        });
        background.add(addadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 200, 100));

        cartelera.setBackground(new java.awt.Color(255, 255, 255));
        cartelera.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        cartelera.setForeground(new java.awt.Color(153, 153, 153));
        cartelera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cartelera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Clapperboard_85px.png"))); // NOI18N
        cartelera.setText("  Cartelera");
        cartelera.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cartelera.setOpaque(true);
        cartelera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carteleraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                carteleraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                carteleraMouseExited(evt);
            }
        });
        background.add(cartelera, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 200, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void topbarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topbarMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_topbarMouseDragged

    public static int x;
    public static int y;
    private void topbarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topbarMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_topbarMousePressed

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        close.setBackground(new Color(255, 51, 51));
        close.setIcon(new ImageIcon("src/imagenes/Deletewhite_25px.png"));
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        close.setBackground(new Color(255, 255, 255));
        close.setIcon(new ImageIcon("src/imagenes/Delete_25px.png"));
    }//GEN-LAST:event_closeMouseExited

    private void agregarpelisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarpelisMouseClicked
        AddPeliculas ventana=new AddPeliculas();
        this.setVisible(false);
        ventana.setVisible(true);
    }//GEN-LAST:event_agregarpelisMouseClicked

    private void agregarpelisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarpelisMouseEntered
        agregarpelis.setBackground(new Color(240,240,240));
        agregarpelis.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_agregarpelisMouseEntered

    private void agregarpelisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarpelisMouseExited
        agregarpelis.setBackground(new Color(255,255,255));
        agregarpelis.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_agregarpelisMouseExited

    private void pdisponiblesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pdisponiblesMouseClicked
        ListaPeliculas ventana=new ListaPeliculas();
        this.setVisible(false);
        ventana.setVisible(true);
    }//GEN-LAST:event_pdisponiblesMouseClicked

    private void pdisponiblesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pdisponiblesMouseEntered
        pdisponibles.setBackground(new Color(240,240,240));
        pdisponibles.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_pdisponiblesMouseEntered

    private void pdisponiblesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pdisponiblesMouseExited
        pdisponibles.setBackground(new Color(255,255,255));
        pdisponibles.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_pdisponiblesMouseExited

    private void entradasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entradasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_entradasMouseClicked

    private void entradasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entradasMouseEntered
        entradas.setBackground(new Color(240,240,240));
        entradas.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_entradasMouseEntered

    private void entradasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entradasMouseExited
        entradas.setBackground(new Color(255,255,255));
        entradas.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_entradasMouseExited

    private void horariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_horariosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_horariosMouseClicked

    private void horariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_horariosMouseEntered
        horarios.setBackground(new Color(240,240,240));
        horarios.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_horariosMouseEntered

    private void horariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_horariosMouseExited
        horarios.setBackground(new Color(255,255,255));
        horarios.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_horariosMouseExited

    private void addadminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addadminMouseEntered
        addadmin.setBackground(new Color(240,240,240));
        addadmin.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_addadminMouseEntered

    private void addadminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addadminMouseExited
        addadmin.setBackground(new Color(255,255,255));
        addadmin.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_addadminMouseExited

    private void addadminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addadminMouseClicked
        SignUpAdmin s=new SignUpAdmin();
        this.setVisible(false);
        s.setVisible(true);
    }//GEN-LAST:event_addadminMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        LogInAdmin l=new LogInAdmin();
        this.setVisible(false);
        l.setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    private void carteleraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carteleraMouseClicked
        Cartelera c=new Cartelera();
        this.setVisible(false);
        c.setVisible(true);
    }//GEN-LAST:event_carteleraMouseClicked

    private void carteleraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carteleraMouseEntered
        cartelera.setBackground(new Color(240,240,240));
        cartelera.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_carteleraMouseEntered

    private void carteleraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carteleraMouseExited
        cartelera.setBackground(new Color(255,255,255));
        cartelera.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_carteleraMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addadmin;
    private javax.swing.JLabel agregarpelis;
    private javax.swing.JPanel background;
    private javax.swing.JLabel cartelera;
    private javax.swing.JLabel close;
    private javax.swing.JLabel entradas;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel horarios;
    private javax.swing.JLabel hour;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel pdisponibles;
    private javax.swing.JLabel topbar;
    // End of variables declaration//GEN-END:variables
}
