/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cine;

import com.sun.awt.AWTUtilities;
import java.awt.Color;
import java.io.File;
import java.util.Scanner;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Jesus David
 */
public class LogInUsuario extends javax.swing.JFrame {

    /**
     * Creates new form LogInUsuario
     */
    public LogInUsuario() {
        initComponents();
        AWTUtilities.setWindowOpaque(this, false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        volver = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        topbar = new javax.swing.JLabel();
        usertxt = new javax.swing.JTextField();
        separatoruser = new javax.swing.JSeparator();
        user = new javax.swing.JLabel();
        separatorpassw = new javax.swing.JSeparator();
        passwordfield = new javax.swing.JPasswordField();
        password = new javax.swing.JLabel();
        acceder = new javax.swing.JLabel();
        crear = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        volver.setBackground(new java.awt.Color(255, 255, 255));
        volver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Back Arrow_28px.png"))); // NOI18N
        volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        volver.setOpaque(true);
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                volverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                volverMouseExited(evt);
            }
        });
        background.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        title.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        title.setText("Inicio de Sesión: Usuario");
        background.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        close.setBackground(new java.awt.Color(255, 255, 255));
        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Delete_25px.png"))); // NOI18N
        close.setOpaque(true);
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        background.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 40, 40));

        topbar.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        topbar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                topbarMouseDragged(evt);
            }
        });
        topbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                topbarMousePressed(evt);
            }
        });
        background.add(topbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 40));

        usertxt.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        usertxt.setBorder(null);
        usertxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usertxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usertxtFocusLost(evt);
            }
        });
        usertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usertxtActionPerformed(evt);
            }
        });
        background.add(usertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 210, 20));

        separatoruser.setBackground(new java.awt.Color(51, 102, 255));
        separatoruser.setForeground(new java.awt.Color(255, 255, 255));
        background.add(separatoruser, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 210, -1));

        user.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        user.setForeground(new java.awt.Color(51, 102, 255));
        user.setText("Usuario");
        background.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 70, -1));

        separatorpassw.setBackground(new java.awt.Color(204, 204, 204));
        separatorpassw.setForeground(new java.awt.Color(255, 255, 255));
        background.add(separatorpassw, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 210, -1));

        passwordfield.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 8)); // NOI18N
        passwordfield.setBorder(null);
        passwordfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordfieldFocusLost(evt);
            }
        });
        passwordfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordfieldActionPerformed(evt);
            }
        });
        background.add(passwordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 210, 20));

        password.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        password.setForeground(new java.awt.Color(153, 153, 153));
        password.setText("Contraseña");
        background.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, -1, -1));

        acceder.setBackground(new java.awt.Color(255, 255, 255));
        acceder.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 13)); // NOI18N
        acceder.setForeground(new java.awt.Color(51, 102, 255));
        acceder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acceder.setText("Acceder");
        acceder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        acceder.setOpaque(true);
        acceder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accederMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accederMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accederMouseExited(evt);
            }
        });
        background.add(acceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 70, 30));

        crear.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 13)); // NOI18N
        crear.setForeground(new java.awt.Color(153, 153, 153));
        crear.setText("Crea una cuenta");
        crear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                crearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                crearMouseExited(evt);
            }
        });
        background.add(crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, -1, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/DU NORDCINEMA.png"))); // NOI18N
        background.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 420, 170));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void topbarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topbarMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_topbarMouseDragged

    public static int x;
    public static int y;
    private void topbarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topbarMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_topbarMousePressed

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        close.setBackground(new Color(255, 51, 51));
        close.setIcon(new ImageIcon("src/imagenes/Deletewhite_25px.png"));
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        close.setBackground(new Color(255, 255, 255));
        close.setIcon(new ImageIcon("src/imagenes/Delete_25px.png"));
    }//GEN-LAST:event_closeMouseExited

    private void usertxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usertxtFocusGained
        separatoruser.setBackground(new Color(51,102,255));
        user.setForeground(new Color(51,102,255));
    }//GEN-LAST:event_usertxtFocusGained

    private void usertxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usertxtFocusLost
        separatoruser.setBackground(new Color(204, 204, 204));
        user.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_usertxtFocusLost

    private void usertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usertxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usertxtActionPerformed

    private void passwordfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordfieldFocusGained
        separatorpassw.setBackground(new Color(51,102,255));
        password.setForeground(new Color(51,102,255));
    }//GEN-LAST:event_passwordfieldFocusGained

    private void passwordfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordfieldFocusLost
        separatorpassw.setBackground(new Color(204, 204, 204));
        password.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_passwordfieldFocusLost

    private void passwordfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordfieldActionPerformed

    }//GEN-LAST:event_passwordfieldActionPerformed

    private void accederMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accederMouseClicked
        if ((usertxt.getText().length() != 0) && (passwordfield.getText().length() != 0)) {
            String usuario = usertxt.getText();
            String password = passwordfield.getText();
            File archivo = new File("usuarios.txt");
            Scanner s = null;
            try {
                boolean sw = false, sw2 = false;
                s = new Scanner(archivo);
                while (s.hasNextLine()) {
                    String linea = s.nextLine();
                    String[] campo = linea.split(",");
                    if (usuario.equals(campo[3]) && password.equals(campo[4])) {
                        sw = true;
                        sw2 = true;
                        break;
                    } else if (usuario.equals(campo[3]) && !password.equals(campo[4])) {
                        sw = true;
                        sw2 = false;
                        break;
                    } else {
                        sw = false;
                        sw2 = false;
                    }

                }
                if ((sw == false) && (sw2 == false)) {
                    JOptionPane.showMessageDialog(null, "El usuario no existe", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                } else if ((sw == true) && (sw2 == false)) {
                    JOptionPane.showMessageDialog(null, "Contraseña incorrecta", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                } else if (sw == true && sw2 == true) {
                    this.setVisible(false);
                    User ventana=new User();
                    ventana.setVisible(true); 
                }
            } catch (Exception ex) {
                System.out.println("Mensaje:" + ex.getMessage());
            } finally {
                try {
                    if (s != null) {
                        s.close();
                    }
                } catch (Exception ex2) {
                    System.out.println("Mensaje 2:" + ex2.getMessage());
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "No deben haber campos vacios", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_accederMouseClicked

    private void accederMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accederMouseEntered
        acceder.setBackground(new Color(51,102,255));
        acceder.setForeground(Color.WHITE);
    }//GEN-LAST:event_accederMouseEntered

    private void accederMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accederMouseExited
        acceder.setBackground(Color.WHITE);
        acceder.setForeground(new Color(51,102,255));
    }//GEN-LAST:event_accederMouseExited

    private void crearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearMouseEntered
        crear.setForeground(new Color(51,51,255));
    }//GEN-LAST:event_crearMouseEntered

    private void crearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearMouseExited
        crear.setForeground(new Color(153,153,153));
    }//GEN-LAST:event_crearMouseExited

    private void crearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearMouseClicked
        SignUpUsuario ventana=new SignUpUsuario();
        this.setVisible(false);
        ventana.setVisible(true);
    }//GEN-LAST:event_crearMouseClicked

    private void volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseClicked
        LogIn u = new LogIn();
        this.setVisible(false);
        u.setVisible(true);
    }//GEN-LAST:event_volverMouseClicked

    private void volverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseEntered
        volver.setBackground(new Color(231, 231, 231));
    }//GEN-LAST:event_volverMouseEntered

    private void volverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseExited
        volver.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_volverMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogInUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acceder;
    private javax.swing.JPanel background;
    private javax.swing.JLabel close;
    private javax.swing.JLabel crear;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField passwordfield;
    private javax.swing.JSeparator separatorpassw;
    private javax.swing.JSeparator separatoruser;
    private javax.swing.JLabel title;
    private javax.swing.JLabel topbar;
    private javax.swing.JLabel user;
    private javax.swing.JTextField usertxt;
    private javax.swing.JLabel volver;
    // End of variables declaration//GEN-END:variables
}
