/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cine;

import com.sun.awt.AWTUtilities;
import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Jesus David
 */
public class Sala extends javax.swing.JFrame {

    /**
     * Creates new form Sala
     */
    public Sala() {
        initComponents();
        AWTUtilities.setWindowOpaque(this, false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        A1 = new javax.swing.JLabel();
        A2 = new javax.swing.JLabel();
        A3 = new javax.swing.JLabel();
        A4 = new javax.swing.JLabel();
        A5 = new javax.swing.JLabel();
        A6 = new javax.swing.JLabel();
        A7 = new javax.swing.JLabel();
        A8 = new javax.swing.JLabel();
        A9 = new javax.swing.JLabel();
        A10 = new javax.swing.JLabel();
        B1 = new javax.swing.JLabel();
        B2 = new javax.swing.JLabel();
        B3 = new javax.swing.JLabel();
        B4 = new javax.swing.JLabel();
        B5 = new javax.swing.JLabel();
        B6 = new javax.swing.JLabel();
        B7 = new javax.swing.JLabel();
        B8 = new javax.swing.JLabel();
        B9 = new javax.swing.JLabel();
        B10 = new javax.swing.JLabel();
        C1 = new javax.swing.JLabel();
        C2 = new javax.swing.JLabel();
        C3 = new javax.swing.JLabel();
        C4 = new javax.swing.JLabel();
        C5 = new javax.swing.JLabel();
        C6 = new javax.swing.JLabel();
        C7 = new javax.swing.JLabel();
        C8 = new javax.swing.JLabel();
        C9 = new javax.swing.JLabel();
        C10 = new javax.swing.JLabel();
        D1 = new javax.swing.JLabel();
        D2 = new javax.swing.JLabel();
        D3 = new javax.swing.JLabel();
        D4 = new javax.swing.JLabel();
        D5 = new javax.swing.JLabel();
        D6 = new javax.swing.JLabel();
        D7 = new javax.swing.JLabel();
        D8 = new javax.swing.JLabel();
        D9 = new javax.swing.JLabel();
        D10 = new javax.swing.JLabel();
        E1 = new javax.swing.JLabel();
        E2 = new javax.swing.JLabel();
        E3 = new javax.swing.JLabel();
        E4 = new javax.swing.JLabel();
        E5 = new javax.swing.JLabel();
        E6 = new javax.swing.JLabel();
        E7 = new javax.swing.JLabel();
        E8 = new javax.swing.JLabel();
        E9 = new javax.swing.JLabel();
        E10 = new javax.swing.JLabel();
        F1 = new javax.swing.JLabel();
        F2 = new javax.swing.JLabel();
        F3 = new javax.swing.JLabel();
        F4 = new javax.swing.JLabel();
        F5 = new javax.swing.JLabel();
        F6 = new javax.swing.JLabel();
        F7 = new javax.swing.JLabel();
        F8 = new javax.swing.JLabel();
        F9 = new javax.swing.JLabel();
        F10 = new javax.swing.JLabel();
        G1 = new javax.swing.JLabel();
        G2 = new javax.swing.JLabel();
        G3 = new javax.swing.JLabel();
        G4 = new javax.swing.JLabel();
        G5 = new javax.swing.JLabel();
        G6 = new javax.swing.JLabel();
        G7 = new javax.swing.JLabel();
        G8 = new javax.swing.JLabel();
        G9 = new javax.swing.JLabel();
        G10 = new javax.swing.JLabel();
        H1 = new javax.swing.JLabel();
        H2 = new javax.swing.JLabel();
        H3 = new javax.swing.JLabel();
        H4 = new javax.swing.JLabel();
        H5 = new javax.swing.JLabel();
        H6 = new javax.swing.JLabel();
        H7 = new javax.swing.JLabel();
        H8 = new javax.swing.JLabel();
        H9 = new javax.swing.JLabel();
        H10 = new javax.swing.JLabel();
        I1 = new javax.swing.JLabel();
        I2 = new javax.swing.JLabel();
        I3 = new javax.swing.JLabel();
        I4 = new javax.swing.JLabel();
        I5 = new javax.swing.JLabel();
        I6 = new javax.swing.JLabel();
        I7 = new javax.swing.JLabel();
        I8 = new javax.swing.JLabel();
        I9 = new javax.swing.JLabel();
        I10 = new javax.swing.JLabel();
        J1 = new javax.swing.JLabel();
        J2 = new javax.swing.JLabel();
        J3 = new javax.swing.JLabel();
        J4 = new javax.swing.JLabel();
        J5 = new javax.swing.JLabel();
        J6 = new javax.swing.JLabel();
        J7 = new javax.swing.JLabel();
        J8 = new javax.swing.JLabel();
        J9 = new javax.swing.JLabel();
        J10 = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        topbar = new javax.swing.JLabel();
        save = new javax.swing.JLabel();
        pantalla = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        title.setText("Reserva de Asientos");
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 180, 26));

        A1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        A1.setOpaque(true);
        A1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A1MouseClicked(evt);
            }
        });
        jPanel1.add(A1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 30, -1));

        A2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(A2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 30, -1));

        A3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(A3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 30, -1));

        A4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(A4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 30, -1));

        A5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(A5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 30, -1));

        A6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(A6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 30, -1));

        A7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(A7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 30, -1));

        A8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(A8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 30, -1));

        A9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(A9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 30, -1));

        A10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(A10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 30, -1));

        B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 30, -1));

        B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 30, -1));

        B3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(B3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 30, -1));

        B4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(B4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 30, -1));

        B5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(B5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 30, -1));

        B6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(B6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 30, -1));

        B7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(B7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 30, -1));

        B8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(B8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 30, -1));

        B9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(B9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 30, -1));

        B10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(B10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 30, -1));

        C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 30, -1));

        C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 30, -1));

        C3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(C3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 30, -1));

        C4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(C4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 30, -1));

        C5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(C5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 30, -1));

        C6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(C6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 30, -1));

        C7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(C7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 30, -1));

        C8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(C8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 30, -1));

        C9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(C9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 30, -1));

        C10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(C10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 30, -1));

        D1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(D1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 30, -1));

        D2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(D2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 30, -1));

        D3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(D3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 30, -1));

        D4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(D4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 30, -1));

        D5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(D5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 30, -1));

        D6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(D6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 30, -1));

        D7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(D7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 30, -1));

        D8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(D8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 30, -1));

        D9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(D9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 30, -1));

        D10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(D10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 30, -1));

        E1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(E1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 30, -1));

        E2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(E2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 30, -1));

        E3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(E3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 30, -1));

        E4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(E4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 30, -1));

        E5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(E5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 30, -1));

        E6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(E6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 30, -1));

        E7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(E7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 30, -1));

        E8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(E8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 30, -1));

        E9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(E9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 30, -1));

        E10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(E10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 30, -1));

        F1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(F1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 30, -1));

        F2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(F2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 30, -1));

        F3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(F3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 30, -1));

        F4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(F4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 30, -1));

        F5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(F5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 30, -1));

        F6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(F6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 30, -1));

        F7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(F7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 30, -1));

        F8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(F8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 30, -1));

        F9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(F9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 30, -1));

        F10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(F10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 30, -1));

        G1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(G1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 30, -1));

        G2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(G2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 30, -1));

        G3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(G3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 30, -1));

        G4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(G4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 30, -1));

        G5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(G5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 30, -1));

        G6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(G6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 30, -1));

        G7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(G7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 30, -1));

        G8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(G8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 30, -1));

        G9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(G9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 30, -1));

        G10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(G10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 30, -1));

        H1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(H1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 30, -1));

        H2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(H2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 30, -1));

        H3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(H3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 30, -1));

        H4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(H4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 30, -1));

        H5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(H5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 30, -1));

        H6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(H6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 30, -1));

        H7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(H7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 30, -1));

        H8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(H8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 30, -1));

        H9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(H9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 30, -1));

        H10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(H10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 30, -1));

        I1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(I1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 30, -1));

        I2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(I2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 30, -1));

        I3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(I3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 30, -1));

        I4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(I4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 30, -1));

        I5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(I5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 30, -1));

        I6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(I6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 30, -1));

        I7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(I7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 30, -1));

        I8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(I8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 30, -1));

        I9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(I9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 30, -1));

        I10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(I10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 30, -1));

        J1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(J1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 30, -1));

        J2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(J2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 30, -1));

        J3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(J3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 30, -1));

        J4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(J4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 30, -1));

        J5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(J5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 30, -1));

        J6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(J6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 30, -1));

        J7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(J7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 30, -1));

        J8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(J8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 30, -1));

        J9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(J9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 30, -1));

        J10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disponible.png"))); // NOI18N
        jPanel1.add(J10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, 30, -1));

        close.setBackground(new java.awt.Color(255, 255, 255));
        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Delete_25px.png"))); // NOI18N
        close.setOpaque(true);
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 40, 40));

        topbar.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        topbar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                topbarMouseDragged(evt);
            }
        });
        topbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                topbarMousePressed(evt);
            }
        });
        jPanel1.add(topbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 40));

        save.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        save.setText("Guardar");
        save.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, 70, 30));

        pantalla.setBackground(new java.awt.Color(153, 153, 153));
        pantalla.setOpaque(true);
        jPanel1.add(pantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 430, 10));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jLabel1.setText("Pantalla");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        close.setBackground(new Color(255, 51, 51));
        close.setIcon(new ImageIcon("src/imagenes/Deletewhite_25px.png"));
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        close.setBackground(new Color(255, 255, 255));
        close.setIcon(new ImageIcon("src/imagenes/Delete_25px.png"));
    }//GEN-LAST:event_closeMouseExited

    private void topbarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topbarMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_topbarMouseDragged

    public static int x;
    public static int y;
    
    private void topbarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topbarMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_topbarMousePressed

    private void A1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A1MouseClicked
        if (evt.getClickCount() == 2) {
            ImageIcon i;
            if (("src/imagenes/disponible.png").equals(A1.getIcon().toString())) {
                A1.setIcon(new ImageIcon("src/imagenes/reservado.png")); 
            }else{
                A1.setIcon(new ImageIcon("src/imagenes/disponible.png")); 
            }
        }
    }//GEN-LAST:event_A1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sala().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A1;
    private javax.swing.JLabel A10;
    private javax.swing.JLabel A2;
    private javax.swing.JLabel A3;
    private javax.swing.JLabel A4;
    private javax.swing.JLabel A5;
    private javax.swing.JLabel A6;
    private javax.swing.JLabel A7;
    private javax.swing.JLabel A8;
    private javax.swing.JLabel A9;
    private javax.swing.JLabel B1;
    private javax.swing.JLabel B10;
    private javax.swing.JLabel B2;
    private javax.swing.JLabel B3;
    private javax.swing.JLabel B4;
    private javax.swing.JLabel B5;
    private javax.swing.JLabel B6;
    private javax.swing.JLabel B7;
    private javax.swing.JLabel B8;
    private javax.swing.JLabel B9;
    private javax.swing.JLabel C1;
    private javax.swing.JLabel C10;
    private javax.swing.JLabel C2;
    private javax.swing.JLabel C3;
    private javax.swing.JLabel C4;
    private javax.swing.JLabel C5;
    private javax.swing.JLabel C6;
    private javax.swing.JLabel C7;
    private javax.swing.JLabel C8;
    private javax.swing.JLabel C9;
    private javax.swing.JLabel D1;
    private javax.swing.JLabel D10;
    private javax.swing.JLabel D2;
    private javax.swing.JLabel D3;
    private javax.swing.JLabel D4;
    private javax.swing.JLabel D5;
    private javax.swing.JLabel D6;
    private javax.swing.JLabel D7;
    private javax.swing.JLabel D8;
    private javax.swing.JLabel D9;
    private javax.swing.JLabel E1;
    private javax.swing.JLabel E10;
    private javax.swing.JLabel E2;
    private javax.swing.JLabel E3;
    private javax.swing.JLabel E4;
    private javax.swing.JLabel E5;
    private javax.swing.JLabel E6;
    private javax.swing.JLabel E7;
    private javax.swing.JLabel E8;
    private javax.swing.JLabel E9;
    private javax.swing.JLabel F1;
    private javax.swing.JLabel F10;
    private javax.swing.JLabel F2;
    private javax.swing.JLabel F3;
    private javax.swing.JLabel F4;
    private javax.swing.JLabel F5;
    private javax.swing.JLabel F6;
    private javax.swing.JLabel F7;
    private javax.swing.JLabel F8;
    private javax.swing.JLabel F9;
    private javax.swing.JLabel G1;
    private javax.swing.JLabel G10;
    private javax.swing.JLabel G2;
    private javax.swing.JLabel G3;
    private javax.swing.JLabel G4;
    private javax.swing.JLabel G5;
    private javax.swing.JLabel G6;
    private javax.swing.JLabel G7;
    private javax.swing.JLabel G8;
    private javax.swing.JLabel G9;
    private javax.swing.JLabel H1;
    private javax.swing.JLabel H10;
    private javax.swing.JLabel H2;
    private javax.swing.JLabel H3;
    private javax.swing.JLabel H4;
    private javax.swing.JLabel H5;
    private javax.swing.JLabel H6;
    private javax.swing.JLabel H7;
    private javax.swing.JLabel H8;
    private javax.swing.JLabel H9;
    private javax.swing.JLabel I1;
    private javax.swing.JLabel I10;
    private javax.swing.JLabel I2;
    private javax.swing.JLabel I3;
    private javax.swing.JLabel I4;
    private javax.swing.JLabel I5;
    private javax.swing.JLabel I6;
    private javax.swing.JLabel I7;
    private javax.swing.JLabel I8;
    private javax.swing.JLabel I9;
    private javax.swing.JLabel J1;
    private javax.swing.JLabel J10;
    private javax.swing.JLabel J2;
    private javax.swing.JLabel J3;
    private javax.swing.JLabel J4;
    private javax.swing.JLabel J5;
    private javax.swing.JLabel J6;
    private javax.swing.JLabel J7;
    private javax.swing.JLabel J8;
    private javax.swing.JLabel J9;
    private javax.swing.JLabel close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pantalla;
    private javax.swing.JLabel save;
    private javax.swing.JLabel title;
    private javax.swing.JLabel topbar;
    // End of variables declaration//GEN-END:variables
}
